const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")
const ai = new GoogleGenAI({
    apiKey: process.env.Google_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    matchScore:z.number().describe("The match score between the candidate and the job description, ranging from 0 to 100"),
    technicalQuestions:z.array(z.object({
        question:z.string().describe("The technical question can be asked in the interview"),
        intention:z.string().describe("The intention of interviewer behind asking this question"),
        answer:z.string().describe("The answer to the technical question")
    })).describe("A list of technical questions that can be asked in the interview"),
    behavioralQuestions:z.array(z.object({
        question:z.string().describe("The behavioral question can be asked in the interview"),
        intention:z.string().describe("The intention of interviewer behind asking this question"),
        answer:z.string().describe("The answer to the behavioral question")
    })).describe("A list of behavioral questions that can be asked in the interview"),
    skillGaps:z.array(z.object({
        skill:z.string().describe("The skill that the candidate is lacking"),
        severity:z.enum(["Low","Medium","High"]).describe("The severity of the skill gap"),
    })).describe("A list of skill gaps that the candidate has"),
    preparationPlan:z.array(z.object({
        day:z.number().describe("The day number in the preparation plan, starting from 1"),
        focus:z.string().describe("The focus area for the day"),
        tasks:z.array(z.string()).describe("A list of tasks to be completed on the day")
    })).describe("A day-wise preparation plan for the candidate to improve their skills and knowledge"),
    title: z.string().describe("The totle of the job for which the interview report is generated"),

})


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


    // const prompt = `Generate an interview report for a candidate with the following details:
    //                     Resume: ${resume}
    //                     Self Description: ${selfDescription}
    //                     Job Description: ${jobDescription}`
    const prompt = `
You are an experienced technical recruiter.

Analyze the candidate based on:

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}

Generate:

1. Match score (0-100)
2. 8-10 technical interview questions with intentions and ideal answers
3. 5 behavioral interview questions with intentions and ideal answers
4. Skill gaps with severity
5. A 3-30 days preparation plan

Return only valid JSON following the provided schema.
`;

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema),
        }
    })

    return JSON.parse(response.text)


}

async function generatePdfFromHtml(htmlContent){
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent,{waitUntil:"networkidle0"})

    const pdfBuffer = await page.pdf({format:"A4",margin:{top:"20mm",bottom:"20mm",left:"15mm",right:"15mm"}})

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({resume,selfDescription,jobDescription}){
    const resumePdfSchema = z.object({
        html:z.string().describe("The HTML content of the resume which will be converted to PDF using puppeteer")
    })

    const prompt = `Generate a resume for a candidate with the following details:
    Resume: ${resume}
    Self Description: ${selfDescription}
    Job Description: ${jobDescription}
    the response should be a JSON object with a single key "html" which contains the HTML content of the resume which will be converted to PDF using puppeteer
    The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visible
    the contennt of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
    you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
    The content should be ATS friendly, i.e. it should be easily parsable by ATS system without losing important information.
    The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
    `

    const response = await ai.models.generateContent({
        model:"gemini-3-flash-preview",
        contents: prompt,
        config:{
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema)
        }
    })

    const jsonContent = JSON.parse(response.text)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
    return pdfBuffer
}

module.exports = {generateInterviewReport,generateResumePdf}